apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: webapp-mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
    default-character-set=utf8
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
    default-character-set=utf8

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: webapp-sql
    tier: backend
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
  clusterIP: None


---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: webapp-sql
    tier: backend
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqldb
  labels:
    app: webapp-sql
    tier: backend
spec:
  selector:
    matchLabels:
      app: webapp-sql
      tier: backend
  replicas: 3
  serviceName: mysql  
  template:
    metadata:
      labels:
        app: webapp-sql
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_SERVICE_HOST
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: chat
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: password
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: conf
          mountPath: /etc/mysql/conf.d

      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: mysql
