apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: backend
  labels:
    type: local
spec:
  storageClassName: ssd
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: backend
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
